### ISSUE TITLE
我该如何使用

### ISSUE THREAD

**Issue by Mc203** [Alien-Stan/APEX_AI#6]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

我使用了python启动它，但没有任何反应

**Comment by Mc203** [comment]
I mean, how do I use the author's AI

**Comment by Alien-Stan** [comment]
运行main函数即可

**Comment by Sarcasmjoker** [comment]
> 运行main函数即可

需要以下文件，请问您有么
'G:\yolov5\yolov5-6.1\runs\train\exp22\weights\best.pt'
