### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Mc203** [Alien-Stan/APEX_AI#7]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

我已经成功打开了它，但是它并没有如何作用

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by koi128bit** [comment]
由于作者没有将检测窗口居中，所以需要更改x, y = (1920, 1080)，即全屏检测。
另外检查自己的GPU是否达到要求
