### ISSUE TITLE
在开启lock on后提示ValueError: attempt to get argmax of an empty sequence并且关闭debug窗口

### ISSUE THREAD

**Issue by koi128bit** [Alien-Stan/APEX_AI#9]
### Search before asking

- [ ] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

在开启lock on后提示ValueError: attempt to get argmax of an empty sequence并且关闭debug窗口

**Comment by Sarcasmjoker** [comment]
需要以下文件，请问您有么
'G:\yolov5\yolov5-6.1\runs\train\exp22\weights\best.pt'

**Comment by koi128bit** [comment]
> 

那个文件夹里有，需要自己改位置
